# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: portal.proto
# Protobuf Python Version: 7.35.0-rc1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '-rc1',
    'portal.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cportal.proto\x12\x06portal\"\x1f\n\x0cTradeRequest\x12\x0f\n\x07item_id\x18\x01 \x01(\x05\"1\n\rTradeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"(\n\x13InventoryGetRequest\x12\x11\n\tplayer_id\x18\x01 \x01(\t\"\'\n\x04Item\x12\x0f\n\x07item_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x05\"J\n\x14InventoryGetResponse\x12\x11\n\tplayer_id\x18\x01 \x01(\t\x12\x1f\n\tinventory\x18\x02 \x03(\x0b\x32\x0c.portal.Item\"r\n\x17InventoryAddItemRequest\x12\x11\n\tplayer_id\x18\x01 \x01(\t\x12\x0f\n\x07item_id\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x05\x12\x11\n\tmax_stack\x18\x04 \x01(\x05\x12\x10\n\x08order_id\x18\x05 \x01(\t\"\x89\x01\n\x1dInventoryAddItemToSlotRequest\x12\x11\n\tplayer_id\x18\x01 \x01(\t\x12\x0f\n\x07item_id\x18\x02 \x01(\t\x12\x0f\n\x07slot_id\x18\x03 \x01(\x05\x12\x0e\n\x06\x61mount\x18\x04 \x01(\x05\x12\x11\n\tmax_stack\x18\x05 \x01(\x05\x12\x10\n\x08order_id\x18\x06 \x01(\t*|\n\x07GameMsg\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x11\n\rTRADE_REQUEST\x10\x0c\x12\x19\n\x15INVENTORY_GET_REQUEST\x10\x15\x12\x16\n\x12INVENTORY_ADD_ITEM\x10\x17\x12\x1e\n\x1aINVENTORY_ADD_ITEM_TO_SLOT\x10\x18\x42\"Z github.com/mercury/cmd/portal/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'portal_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z github.com/mercury/cmd/portal/pb'
  _globals['_GAMEMSG']._serialized_start=523
  _globals['_GAMEMSG']._serialized_end=647
  _globals['_TRADEREQUEST']._serialized_start=24
  _globals['_TRADEREQUEST']._serialized_end=55
  _globals['_TRADERESPONSE']._serialized_start=57
  _globals['_TRADERESPONSE']._serialized_end=106
  _globals['_INVENTORYGETREQUEST']._serialized_start=108
  _globals['_INVENTORYGETREQUEST']._serialized_end=148
  _globals['_ITEM']._serialized_start=150
  _globals['_ITEM']._serialized_end=189
  _globals['_INVENTORYGETRESPONSE']._serialized_start=191
  _globals['_INVENTORYGETRESPONSE']._serialized_end=265
  _globals['_INVENTORYADDITEMREQUEST']._serialized_start=267
  _globals['_INVENTORYADDITEMREQUEST']._serialized_end=381
  _globals['_INVENTORYADDITEMTOSLOTREQUEST']._serialized_start=384
  _globals['_INVENTORYADDITEMTOSLOTREQUEST']._serialized_end=521
# @@protoc_insertion_point(module_scope)
