// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0--rc1
// source: portal.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GameMsg int32

const (
	GameMsg_UNKNOWN       GameMsg = 0
	GameMsg_TRADE_REQUEST GameMsg = 12
	// Inventory Messages
	GameMsg_INVENTORY_GET_REQUEST      GameMsg = 21
	GameMsg_INVENTORY_ADD_ITEM         GameMsg = 23
	GameMsg_INVENTORY_ADD_ITEM_TO_SLOT GameMsg = 24
)

// Enum value maps for GameMsg.
var (
	GameMsg_name = map[int32]string{
		0:  "UNKNOWN",
		12: "TRADE_REQUEST",
		21: "INVENTORY_GET_REQUEST",
		23: "INVENTORY_ADD_ITEM",
		24: "INVENTORY_ADD_ITEM_TO_SLOT",
	}
	GameMsg_value = map[string]int32{
		"UNKNOWN":                    0,
		"TRADE_REQUEST":              12,
		"INVENTORY_GET_REQUEST":      21,
		"INVENTORY_ADD_ITEM":         23,
		"INVENTORY_ADD_ITEM_TO_SLOT": 24,
	}
)

func (x GameMsg) Enum() *GameMsg {
	p := new(GameMsg)
	*p = x
	return p
}

func (x GameMsg) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameMsg) Descriptor() protoreflect.EnumDescriptor {
	return file_portal_proto_enumTypes[0].Descriptor()
}

func (GameMsg) Type() protoreflect.EnumType {
	return &file_portal_proto_enumTypes[0]
}

func (x GameMsg) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameMsg.Descriptor instead.
func (GameMsg) EnumDescriptor() ([]byte, []int) {
	return file_portal_proto_rawDescGZIP(), []int{0}
}

type TradeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        int32                  `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradeRequest) Reset() {
	*x = TradeRequest{}
	mi := &file_portal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeRequest) ProtoMessage() {}

func (x *TradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_portal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeRequest.ProtoReflect.Descriptor instead.
func (*TradeRequest) Descriptor() ([]byte, []int) {
	return file_portal_proto_rawDescGZIP(), []int{0}
}

func (x *TradeRequest) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

type TradeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradeResponse) Reset() {
	*x = TradeResponse{}
	mi := &file_portal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeResponse) ProtoMessage() {}

func (x *TradeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_portal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeResponse.ProtoReflect.Descriptor instead.
func (*TradeResponse) Descriptor() ([]byte, []int) {
	return file_portal_proto_rawDescGZIP(), []int{1}
}

func (x *TradeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TradeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type InventoryGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryGetRequest) Reset() {
	*x = InventoryGetRequest{}
	mi := &file_portal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryGetRequest) ProtoMessage() {}

func (x *InventoryGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_portal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryGetRequest.ProtoReflect.Descriptor instead.
func (*InventoryGetRequest) Descriptor() ([]byte, []int) {
	return file_portal_proto_rawDescGZIP(), []int{2}
}

func (x *InventoryGetRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Amount        int32                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_portal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_portal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_portal_proto_rawDescGZIP(), []int{3}
}

func (x *Item) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *Item) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type InventoryGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Inventory     []*Item                `protobuf:"bytes,2,rep,name=inventory,proto3" json:"inventory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryGetResponse) Reset() {
	*x = InventoryGetResponse{}
	mi := &file_portal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryGetResponse) ProtoMessage() {}

func (x *InventoryGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_portal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryGetResponse.ProtoReflect.Descriptor instead.
func (*InventoryGetResponse) Descriptor() ([]byte, []int) {
	return file_portal_proto_rawDescGZIP(), []int{4}
}

func (x *InventoryGetResponse) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *InventoryGetResponse) GetInventory() []*Item {
	if x != nil {
		return x.Inventory
	}
	return nil
}

type InventoryAddItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	ItemId        string                 `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Amount        int32                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	MaxStack      int32                  `protobuf:"varint,4,opt,name=max_stack,json=maxStack,proto3" json:"max_stack,omitempty"`
	OrderId       string                 `protobuf:"bytes,5,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryAddItemRequest) Reset() {
	*x = InventoryAddItemRequest{}
	mi := &file_portal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryAddItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryAddItemRequest) ProtoMessage() {}

func (x *InventoryAddItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_portal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryAddItemRequest.ProtoReflect.Descriptor instead.
func (*InventoryAddItemRequest) Descriptor() ([]byte, []int) {
	return file_portal_proto_rawDescGZIP(), []int{5}
}

func (x *InventoryAddItemRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *InventoryAddItemRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *InventoryAddItemRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *InventoryAddItemRequest) GetMaxStack() int32 {
	if x != nil {
		return x.MaxStack
	}
	return 0
}

func (x *InventoryAddItemRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type InventoryAddItemToSlotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	ItemId        string                 `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	SlotId        int32                  `protobuf:"varint,3,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	Amount        int32                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	MaxStack      int32                  `protobuf:"varint,5,opt,name=max_stack,json=maxStack,proto3" json:"max_stack,omitempty"`
	OrderId       string                 `protobuf:"bytes,6,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryAddItemToSlotRequest) Reset() {
	*x = InventoryAddItemToSlotRequest{}
	mi := &file_portal_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryAddItemToSlotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryAddItemToSlotRequest) ProtoMessage() {}

func (x *InventoryAddItemToSlotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_portal_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryAddItemToSlotRequest.ProtoReflect.Descriptor instead.
func (*InventoryAddItemToSlotRequest) Descriptor() ([]byte, []int) {
	return file_portal_proto_rawDescGZIP(), []int{6}
}

func (x *InventoryAddItemToSlotRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *InventoryAddItemToSlotRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *InventoryAddItemToSlotRequest) GetSlotId() int32 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

func (x *InventoryAddItemToSlotRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *InventoryAddItemToSlotRequest) GetMaxStack() int32 {
	if x != nil {
		return x.MaxStack
	}
	return 0
}

func (x *InventoryAddItemToSlotRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

var File_portal_proto protoreflect.FileDescriptor

const file_portal_proto_rawDesc = "" +
	"\n" +
	"\fportal.proto\x12\x06portal\"'\n" +
	"\fTradeRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\x05R\x06itemId\"C\n" +
	"\rTradeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"2\n" +
	"\x13InventoryGetRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\"7\n" +
	"\x04Item\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x05R\x06amount\"_\n" +
	"\x14InventoryGetResponse\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12*\n" +
	"\tinventory\x18\x02 \x03(\v2\f.portal.ItemR\tinventory\"\x9f\x01\n" +
	"\x17InventoryAddItemRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\tR\x06itemId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x05R\x06amount\x12\x1b\n" +
	"\tmax_stack\x18\x04 \x01(\x05R\bmaxStack\x12\x19\n" +
	"\border_id\x18\x05 \x01(\tR\aorderId\"\xbe\x01\n" +
	"\x1dInventoryAddItemToSlotRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\tR\x06itemId\x12\x17\n" +
	"\aslot_id\x18\x03 \x01(\x05R\x06slotId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x05R\x06amount\x12\x1b\n" +
	"\tmax_stack\x18\x05 \x01(\x05R\bmaxStack\x12\x19\n" +
	"\border_id\x18\x06 \x01(\tR\aorderId*|\n" +
	"\aGameMsg\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x11\n" +
	"\rTRADE_REQUEST\x10\f\x12\x19\n" +
	"\x15INVENTORY_GET_REQUEST\x10\x15\x12\x16\n" +
	"\x12INVENTORY_ADD_ITEM\x10\x17\x12\x1e\n" +
	"\x1aINVENTORY_ADD_ITEM_TO_SLOT\x10\x18B\"Z github.com/mercury/cmd/portal/pbb\x06proto3"

var (
	file_portal_proto_rawDescOnce sync.Once
	file_portal_proto_rawDescData []byte
)

func file_portal_proto_rawDescGZIP() []byte {
	file_portal_proto_rawDescOnce.Do(func() {
		file_portal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_portal_proto_rawDesc), len(file_portal_proto_rawDesc)))
	})
	return file_portal_proto_rawDescData
}

var file_portal_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_portal_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_portal_proto_goTypes = []any{
	(GameMsg)(0),                          // 0: portal.GameMsg
	(*TradeRequest)(nil),                  // 1: portal.TradeRequest
	(*TradeResponse)(nil),                 // 2: portal.TradeResponse
	(*InventoryGetRequest)(nil),           // 3: portal.InventoryGetRequest
	(*Item)(nil),                          // 4: portal.Item
	(*InventoryGetResponse)(nil),          // 5: portal.InventoryGetResponse
	(*InventoryAddItemRequest)(nil),       // 6: portal.InventoryAddItemRequest
	(*InventoryAddItemToSlotRequest)(nil), // 7: portal.InventoryAddItemToSlotRequest
}
var file_portal_proto_depIdxs = []int32{
	4, // 0: portal.InventoryGetResponse.inventory:type_name -> portal.Item
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_portal_proto_init() }
func file_portal_proto_init() {
	if File_portal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_portal_proto_rawDesc), len(file_portal_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_portal_proto_goTypes,
		DependencyIndexes: file_portal_proto_depIdxs,
		EnumInfos:         file_portal_proto_enumTypes,
		MessageInfos:      file_portal_proto_msgTypes,
	}.Build()
	File_portal_proto = out.File
	file_portal_proto_goTypes = nil
	file_portal_proto_depIdxs = nil
}
